commands:
  AWS-Stack-Command:
    description: "A command to execute and launch EC2 instance & Corresponding Security Group in AWS"
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: 
              aws cloudformation deploy \
                -- template-file ec2_instance.yml \
                -- stack-name create_infrastructure-${CIRCLE_WORKFLOW_ID:0:5} \
                -- region us-west-2  


jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - AWS-Stack-Command

workflow:
  infra_create:
    jobs:
    - create_infrastructure
