version: 2.1

commands:
  print_pipeline_id:
    description: "A command to print out the pipeline id from the circlci built in environment variable"
    steps:
      - echo $CIRCLE_WORKFLOW_ID

defaults: &docker_image 
  docker:
    - image: cimg/base:stable

jobs:
  try_out_commands:
    <<: *docker_image
    
    steps:
      - print_pipeline_id

workflows:
  commands_example:
    jobs:
      - try_out_commands
