version: 2.1

defaults: &docker_image # default name
  docker:
    - image: amazon/aws-cli

commands:
  aws-stack-command:
    description: "A command to execute and launch EC2 instance & Corresponding Security Group in AWS"
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          # | is needed to concatenate the strings
          # has to be '--template-file' and not '-- template file'. No space or error will occur. 
          # It's 'template-body' not 'template-file'

          command: |
            aws cloudformation deploy \
              --template-body ec2_instance.yml \
              --stack-name create_infrastructure-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-west-2  


jobs:
  create_infrastructure:
    <<: *docker_image # calling the default above. 

    steps:
      - aws-stack-command

workflows:
  infra_create:
    jobs:
      - create_infrastructure
