version: 2.1

commands:
  print_pipeline_id:
    description: "A command to print out the pipeline id from the circlci built in environment variable"
    steps:
      - run:
          echo $CIRCLE_WORKFLOW_ID #can put here as is. Or put after run: or put here with command in front of it like command: query to execute

defaults: &docker_image 
  docker:
    - image: cimg/base:stable

jobs:
  try_out_commands:
    <<: *docker_image

    steps:
      - run: print_pipeline_id

workflows:
  commands_example:
    jobs:
      - try_out_commands
